/* -------------------------------------------------------------------------- */
/*                 PEPINO declarative colors for Tailwind config                */
/* -------------------------------------------------------------------------- */
/* Auto-generated by PP-TokenSync · v1.30 */

export const DECLARATIVE_COLORS = {
};